FROM node:20.17.0

WORKDIR /app

COPY package.json package-lock.json ./

COPY . .
# build project
RUN npm run build

# Use Nginx to serve the static files
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html


# Expose the Nginx server port
EXPOSE 80
# Run nginx in foreground
CMD ["nginx", "-g", "daemon off;"]