services:
  db:
    image: mysql:8.0.39
    container_name: surgerywaitinglist-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${GUEST_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d  # Mount the init folder with SQL files
    ports:
      - "3306:3306"
  backend:
    container_name: surgerywaitinglist-backend
    build: ./backend/backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/backend:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
    env_file:
      - ./backend/backend/.env
  frontend:
    container_name: surgerywaitinglist-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true  # Keep stdin open for React
    tty: true         # Allocate a pseudo-TTY
    depends_on:
      - backend    
volumes:
  mysql_data: {}   